nombre = input("Ingrese su nombre: ")
edad = int(input("Cual es tu edad: "))
carrera = input("En que carrera estas?: ")
semestre = int(input("en que semestre estas?: "))
promedio = float(input("Cual es tu promedio"))

print ("Nombre del estudiante: " , nombre)
print ("Edad: ", edad)
print ("Carrera: ", carrera)
print ("Semestre: ", semestre)
print ("Promedio: ", promedio)
